export const FETCH_TABLE = 'FETCH_TABLE';
export const LOAD_TABLE = 'LOAD_TABLE';
export const CHANGE_TABLE_ELEM = 'CHANGE_TABLE_ELEM';
export const SET_CURRENT = 'SET_CURRENT';
export const DO_JOB_WITH_FORMULA = 'DO_JOB_WITH_FORMULA';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
